# https://docs.travis-ci.com/user/getting-started/

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"

# command to install dependencies
install: "pip install -r requirements.txt && pip install tensorflow && pip install nosetests"

env:
  - TEST=Config
  - TEST=Dataset
  - TEST=demos
  - TEST=Device
  - TEST=EngineTask
  - TEST=EngineUtil
  - TEST=GeneratingDataset
  - TEST=hdf_dump
  - TEST=HDFDataset
  - TEST=LearningRateControl
  - TEST=multi_target
  - TEST=MultiBatchBeam
  - TEST=NativeOp
  - TEST=NativeOp_chunk
  - TEST=NativeOp_sparse
  - TEST=NativeOp_subtensor_batched_index
  - TEST=Network
  - TEST=NetworkBaseLayer
  - TEST=NetworkDescription
  - TEST=NetworkLayer
  - TEST=Pretrain
  - TEST=SprintDataset
  - TEST=SprintInterface
  - TEST=TaskSystem
  - TEST=TaskSystem_SharedMem
  - TEST=TFNetworkLayer
  - TEST=TFUtil
  - TEST=TheanoUtil
  - TEST=Util

# command to run tests
script: nosetests tests/test_$TEST.py


